### PR TITLE
Add nix flake

### PR DESCRIPTION
**Pull request by VTimofeenko**
This commit adds a Nix flake to allow easy installation of xremap on Nixos.

It comes with a NixOS module that includes a locked down systemd service and exposes several configuration options for xremap.

### CODE REVIEW

**Comment by k0kubun** [comment]
I have no knowledge of NixOS, so I cannot maintain it in this repository. Are you open to being a maintainer of this code if we create nix-flake repository under xremap org?

**Comment by VTimofeenko** [comment]
Yes, absolutely.

**Comment by k0kubun** [comment]
I created https://github.com/xremap/nix-flake, applied your patch at https://github.com/xremap/nix-flake/pull/1, and invited you to the xremap organization. Can you accept the invitation so that I can make you a maintainer there?

**Comment by VTimofeenko** [comment]
Thanks! Accepted.

**Comment by k0kubun** [comment]
Thank you :+1: Now you have access to write the xremap/nix-flake repository.

**Pull request closed without merging**
