### PR TITLE
add option for unique id

### PR DESCRIPTION
**Pull request by Buttars**
This is a rough draft state. Learned a lot along the way about rust. Please let me know if there's anything I can improve on.

### CODE REVIEW

**Comment by Buttars** [comment]
One concern I have is the refactoring of Args and WatchTargets as well as the several methods I had to change to public to get this to work. 

I'm wondering if the already public get_input_devices method should be refactored to only return devices and exclude all the logging that way it can be used throughout the application without spamming the terminal.

Or if another public method should be exposed to fetch and filter for devices similarly.

**Comment by Buttars** [comment]
I'm happy to continue refining this PR. The reason for the breaking out of the new files was because of the need to expose the Args and WatchTargets structs. Is there a way to expose/import those without moving them out of the files?

**Comment by k0kubun** [comment]
Oh okay. I'm sure it's possible, but let me have a look again tonight to share how it can be done.

**Comment by k0kubun** [comment]
Ugh, I accidentally pushed this change to the actual master since your branch had the same name. I'll reopen another one.

**Pull request merged**
