### PR TITLE
Add timeout_millis for nested remap

### PR DESCRIPTION
**Pull request by k0kubun**
## Example
```yml
keymap:
  - remap:
      C-x:
        remap:
          a: b
        timeout_millis: 1000
```

* C-x -> 500ms -> a
  * b
* C-x -> 1500ms -> a
  * a

### CODE REVIEW

**Comment by 0x78logs** [comment]
that's wonderful. just finished the build and did a couple of tests

here's the config that I have used:

```
keymap:
  - remap:
      j:
        remap:
          k: Esc
        timeout_millis: 200
```

the issue is if I click `j` alone it will never resolve. it stays there... so it makes `j` unusable in my keyboard

another note: it would very nice if we can control the default 500ms.

**Comment by k0kubun** [comment]
> another note: it would be very nice if we can control the default 500ms.

For backward compatibility, when it doesn't have a timeout, it doesn't timeout. I think it's natural from how it's configured, too.

**Comment by 0x78logs** [comment]
but I can't assign a timeout to the first `remap`
I can't do something as the following:

```
keymap:
  - remap:
      j:
        remap:
          k: Esc
    timeout_millis: 200
```

Error: "mapping values are not allowed in the context ..."

**Comment by k0kubun** [comment]
It's top-level, there's nothing to be timed out. All you need is  https://github.com/k0kubun/xremap/pull/82#issuecomment-1085834567.

**Comment by 0x78logs** [comment]
I don't understand, it doesn't work ... pressing `j` and not pressing the following key in the sequence won't resolve to the normal behaviour of `j` thus making `j` in your keyboard not functional.

that's not the behavior of what this feature should achieve.

**Comment by k0kubun** [comment]
In case I confused you by replying a short meesage,

> the issue is if I click j alone it will never resolve. it stays there... so it makes j unusable in my keyboard

I still intend to fix this. However, it doesn't still change the fact that the correct config is:

```yml
keymap:
  - remap:
      j:
        remap:
          k: Esc
        timeout_millis: 200
```

because of how the indent level impacts which key. `timeout_millis` in the above YAML timeouts `j`, so if you're interested in the timeout of `j`, that's what you need.

**Comment by k0kubun** [comment]
I updated the implementation. This YAML:

```yml
keymap:
  - remap:
      j:
        remap:
          k: Esc
        timeout_millis: 200
```

behaves like:

* j -> 100ms -> k
  * Esc
* j -> 300ms -> k
  * j -> k
* j -> any ms -> l
  * j -> l

**Comment by 0x78logs** [comment]
Hello, the config is working as expected now.
however there's still the issue of `j` not resolving if it's not followed by another key.

for example
right now I cannot use my hjkl in vim because it will stuck on `j`

below is the only behavior that's missing 
j -> 200ms or more, user didn't follow with another key press ...
    j

Thank you.

**Comment by k0kubun** [comment]
I updated the implementation. This YAML:

```yml
keymap:
  - remap:
      j:
        remap:
          k: Esc
        timeout_millis: 200
```

behaves like:

* j -> 100ms -> k
  * Esc
* j -> 300ms -> k
  * j -> k
* j -> any ms -> l
  * j -> l
* j -> 300ms
  * j

**Comment by 0x78logs** [comment]
I'm running on the new implementation, so far it is working great.

Give me a couple of days to test it and I'll report if something
misbehaves.

Thank you so much!

**Comment by k0kubun** [comment]
Maybe it's time to release this?

**Comment by 0x78logs** [comment]
Yes, just merge the branch. I'm very happy with the results.
Thank you.

**Comment by k0kubun** [comment]
Thank you for your patience and testing.

**Pull request merged**
