### PR TITLE
Support GNOME 41 and above without `unsafe_mode`.

### PR DESCRIPTION
**Pull request by wilfredwee**
Hello. First of all, thanks for this project. It's amazing and exactly what I'm looking for in Linux.

Since GNOME 41, gnome-shell has [locked down on internal API's](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1970), including
the `Eval` API. To avoid toggling on the `unsafe_mode` in GNOME, we
can instead install a gnome shell extension that provides a 'safe'
introspection API.

SafeIntrospection is a small gnome shell extension I created to expose
the
[Introspect](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/386d25e6f8ce11549526ea3776eb34138fcb3774/data/dbus-interfaces/org.gnome.Shell.Introspect.xml) API.

I have opened an issue with the GNOME Shell team to see if they can
provide this Introspect API publicly instead of having to rely on an
extension here: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5446

I have also updated the README to reflect the current status and new instructions.

### CODE REVIEW

**Comment by k0kubun** [comment]
Hi, thanks for looking into this. Coincidentally, I was working on this issue almost at the same time.

WDYT about https://github.com/k0kubun/xremap/pull/94? While it does require an extra step for installation, it's probably more sensible to avoid relying on internal API.

**Comment by k0kubun** [comment]
Ah, sorry, it seems like yours also uses an extension when you don't want to use `unsafe`. So your patch is actually a superset of mine.

Anyway, if we rely on a third-party extension to make it work, I'd like to keep the full control under xremap's maintainers, so I'd like to still go with https://github.com/k0kubun/xremap/pull/94. When your proposal goes well, I'd be happy to use your implementation without `unsafe`, but meanwhile I'm thinking about just asking users to install an extension.

**Comment by wilfredwee** [comment]
Hahah, interesting coincidence. Yeah that's fine. The extension I created is slightly more generic, but not a huge deal for this project.

**Comment by k0kubun** [comment]
Thank you. When somebody files an issue about obviating extension installation, I might come back to this PR and cherry-pick your code, but for now, let me just go with https://github.com/k0kubun/xremap/pull/94.

I hope https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5446 goes well too!

**Comment by k0kubun** [comment]
I initiated the release of my version as v0.4.0. Please let me know if you find any problems.

**Pull request closed without merging**
